CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    slogan VARCHAR(255),
    description TEXT,
    category VARCHAR(50),
    default_price INTEGER NOT NULL
);
CREATE INDEX product_id_idx on products(id);

CREATE TABLE IF NOT EXISTS  product_features (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    feature VARCHAR(100),
    value VARCHAR(100),
    FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX product_features_id_idx on product_features(id);

CREATE TABLE IF NOT EXISTS  styles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    name VARCHAR(100),
    sale_price VARCHAR(20),
    original_price VARCHAR(20),
    default_style BOOLEAN,
    FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX styles_id_idx on styles(id);

CREATE TABLE IF NOT EXISTS  skus (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    style_id INTEGER,
    size VARCHAR(20),
    quantity INTEGER,
    FOREIGN KEY (style_id) REFERENCES styles(id)
);
CREATE INDEX skus_id_idx on skus(id);

CREATE TABLE IF NOT EXISTS  photos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    style_id INTEGER,
    url TEXT,
    thumbnail_url TEXT,
    FOREIGN KEY (style_id) REFERENCES styles(id)
);
CREATE INDEX photo_id_idx on photos(id);


CREATE TABLE IF NOT EXISTS  related_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    related_product_id INTEGER,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (related_product_id) REFERENCES products(id)
);
CREATE INDEX related_product_id_idx on related_products(id);

CREATE TABLE IF NOT EXISTS cart (
    id SMALLINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    user_session SMALLINT,
    product_id INTEGER,
    active BOOLEAN,
    FOREIGN KEY (product_id) REFERENCES products(id)
);
CREATE INDEX cart_id_idx on cart(id);

-- COPY products
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/product.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY product_features
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/features.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY styles
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/styles.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY skus
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/skus.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY photos
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/photos.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY related_products
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/related.csv'
-- WITH (FORMAT csv, HEADER true, NULL 0);

-- COPY cart
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/database/csv/cart.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');