CREATE TABLE IF NOT EXISTS products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name VARCHAR(100),
    slogan VARCHAR(255),
    description TEXT,
    category VARCHAR(50),
    default_price INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS  product_features (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    feature VARCHAR(100),
    value VARCHAR(100),
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS  styles (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    name VARCHAR(100),
    sale_price VARCHAR(20),
    original_price VARCHAR(20),
    default_style BOOLEAN,
    FOREIGN KEY (product_id) REFERENCES products(id)
);

CREATE TABLE IF NOT EXISTS  skus (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    style_id INTEGER,
    size VARCHAR(20),
    quantity INTEGER,
    FOREIGN KEY (style_id) REFERENCES styles(id)
);

CREATE TABLE IF NOT EXISTS  photos (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    style_id INTEGER,
    url TEXT,
    thumbnail_url TEXT,
    FOREIGN KEY (style_id) REFERENCES styles(id)
);


CREATE TABLE IF NOT EXISTS  related_products (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    product_id INTEGER,
    related_product_id INTEGER,
    FOREIGN KEY (product_id) REFERENCES products(id),
    FOREIGN KEY (related_product_id) REFERENCES products(id)
);

-- COPY products
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/product.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY product_features
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/features.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY styles
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/styles.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY skus
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/skus.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY photos
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/photos.csv'
-- WITH (FORMAT csv, HEADER true, NULL 'null');

-- COPY related_products
-- FROM '/Users/davidzhang/Desktop/HackReactor/RFP2212/product_service/src/data/related.csv'
-- WITH (FORMAT csv, HEADER true, NULL 0);